productos = [ 

{ id: 1 , 
nombre_producto: 'Licuadora' , 
marca : 'Oster' ,
urlImage: './imagenes/1.jpg', 
description: 'Las icónicas licuadoras OSTER son sinónimo de eficiencia y durabilidad. Su nuevo diseño moderno le brinda a toda la familia una mejor experiencia gracias a sus controles le permitirá hacer las bebidas más heladas con su revolucionaria cuchilla que tritura hielo. Como en todos nuestros modelos, el exclusivo sistema All-Metal Drive garantiza una mayor duración .Disfrutaras una inolvidable experiencia con multiples recetas de batidos y jugos con la mejor calidad adicional dara un toque especial a espacios de su cocina.' ,
duration: '141 min',
precio: '$ 359.900', 
amount: 10 ,
idTrailer: 'FDhvbIqTQwI' },  

{ id: 2 , 
nombre_producto: 'Cafetera' , 
marca : 'Oster' ,
urlImage: './imagenes/2.jpg', 
description: 'Presentamos la Cafetera para espresso OSTER Perfect Brew de 15 bares con molino integrado.| Una máquina de espresso para el hogar que reúne todo lo que necesitas para preparar en casa un café de excelente sabor y aroma al estilo de los baristas profesionales. Ahora todos, desde principiantes hasta aspirantes a baristas, pueden obtener fácilmente un espresso perfecto. ¡Compra la tuya acá!' ,
duration: '99 min',
precio: '$ 2.199.900', 
amount: 5 ,
idTrailer: 'IblLmbGxw1Q' },

{ id: 3 , 
nombre_producto: 'Ventilador' , 
marca : 'SAMURAI' ,
urlImage: './imagenes/3.jpg', 
description: 'Este ventilador de 18 pulgadas cuenta con 3 velocidades que permiten elegir el flujo de aire deseado. Teniendo en cuenta que sus niveles de ruido son bajos. Tiene un potente flujo de aire, ya que su motor es de 70W. Sus Mallas son muy seguras ya que no entran en contacto con sus helices. Además, sus mallas frontales son removibles, facilitanto la limpieza de los mismos. Cuentan con una oscilación vertical para una mayor y mejor distibución del aire. cuentan con un fácil y seguro sistema que permite ajustar la inclinación vertical.' ,
duration: '126 min',
precio: '$ 199.900', 
amount: 7 ,
idTrailer: 'vszKTDSdH_I' },

{ id: 4 ,
nombre_producto: 'Lavadora' , 
marca : 'SAMSUNG' ,
urlImage: './imagenes/4.jpg', 
description: 'La lavadora carga superior de 19Kg Samsung te brinda una amplia capacidad de lavado que te permite reducir la frecuencia de uso, incluso puedes incluir artículos realmente grandes. Maneja un motor Digital Inverter con 20 años de garantía que te permite tener un desempeño más potente y consume menos energía. Además, puedes personalizar tu ciclo de lavado de acuerdo a tus necesidades. Así mismo, tiene un compartimiento que disuelve el detergente en polvo antes de echarlo a la lavadora.' ,
duration: '105 min',
precio: '$ 1.899.000', 
amount: 3 ,
idTrailer: 'Amzj7xll3Aw' },

{ id: 5 , 
nombre_producto: 'Nevera' , 
marca : 'HACEB' ,
urlImage: './imagenes/5.jpg', 
description: 'La nevera HACEB No Frost de 379 Litros color Gris Plomo con su tecnología Vital Fresh que neutraliza la propagación de bacterias y cuida la salud de tu familia mientras mantiene tus alimentos frescos por más tiempo.* Además, cuenta con panel digital interno con control digital de temperatura y función de congelamiento rápido, sistema de bandejas independientes con control de humedad ¡Aprovecha esta oportunidad y renueva tu hogar con la mejor tecnología en conservación de alimentos! ¡Compra ya y disfruta la nevera HACEB!' ,
duration: '117 min',
precio: '$ 2.077.900', 
amount: 3 ,
idTrailer: 'NjBGzJ5FFmI' },

{ id: 6 , 
nombre_producto: 'Freidora' , 
marca : 'OSTER' ,
urlImage: './imagenes/6.jpg', 
description: '¡Eleva la preparación de tus alimentos! La freidora de aire OSTER digital con capacidad de 4L incluye una bandeja de freír con aire extraíble con revestimiento antiadherente DiamondForce para más espacio y una fácil limpieza. Nuestro revestimiento de Oster DiamondForce está reforzado e infundido con partículas de diamante que forman una matriz estructural, creando un revestimiento 12 veces más duradero y resistente a rayaduras y hasta 15 veces más fácil de limpiar. Ven por la tuya!' ,
duration: '144 min',
precio: '$ 359.900', 
amount: 5 ,
idTrailer: 'LmC5pxr9JZY' },

{ id: 7 , 
nombre_producto: 'Estufa' , 
marca : 'HACEB' ,
urlImage: './imagenes/7.jpg', 
description: 'La estufa Romero HACEB Torre negra gas natural, logra recetas más rápidas con su fogón 35% más potente y de manera segura con sus parrillas antideslizantes. Cocinar en el horno ahora será mejor gracias a su visor 65% más amplio y hazlo de forma segura evitando la fuga de gas. ¡Cómprala ahora! disfruta de las mejores recetas.' ,
duration: '144 min',
precio: '$ 620.900', 
amount: 5 ,
idTrailer: 'LmC5pxr9JZY' },

{ id: 8 , 
nombre_producto: 'Aspiradora' , 
marca : 'ELECTROLUX' ,
urlImage: './imagenes/8.jpg', 
description: 'La Aspiradora Vertical con cable STK14 Electrolux Power Speed su hogar de manera simple y eficiente. Con 2 posibilidades de uso, como aspiradora vertical y manual, tiene 2 veces más poder de limpieza, y brinda un mayor cuidado a para su familia, ya que está equipado con Filtro HEPA Allergy Protect, que retiene alérgenos, ácaros y hongos, devolviendo más aire puro y seguro para su medio ambiente.' ,
duration: '144 min',
precio: '$ 169.900', 
amount: 5 ,
idTrailer: 'LmC5pxr9JZY' },
    
]
