productos = [ 

{ id: 1 , 
nombre_producto: 'Licuadora' , 
nombre_completo : 'Licuadora OSTER Clásica BLST4655 Plateado' ,
marca : 'Oster' ,
urlImage: './imagenes/1.jpg', 
description: 'Las icónicas licuadoras OSTER son sinónimo de eficiencia y durabilidad. Su nuevo diseño moderno le brinda a toda la familia una mejor experiencia gracias a sus controles le permitirá hacer las bebidas más heladas con su revolucionaria cuchilla que tritura hielo. Como en todos nuestros modelos, el exclusivo sistema All-Metal Drive garantiza una mayor duración .Disfrutaras una inolvidable experiencia con multiples recetas de batidos y jugos con la mejor calidad adicional dara un toque especial a espacios de su cocina.' ,
caracteristicas: 'Motor 6 veces más duradero que le garantiza larga vida a la licuadora;Vaso de Vidrio 1,25 Lts_Resistente;Acople Metalico 10 vecesa mas fuerte;Perilla 50% más grande para mejor ergonomía;Revoucionaria Cuchilla trituradora de Hielo',
precio: '$ 359.900' },  

{ id: 2 , 
nombre_producto: 'Cafetera' , 
nombre_completo : 'Cafetera OSTER Expresso con Molino Integrado BVSTEM7300 Plateado' ,
marca : 'Oster' ,
urlImage: './imagenes/2.jpg', 
description: 'Presentamos la Cafetera para espresso OSTER Perfect Brew de 15 bares con molino integrado.| Una máquina de espresso para el hogar que reúne todo lo que necesitas para preparar en casa un café de excelente sabor y aroma al estilo de los baristas profesionales. Ahora todos, desde principiantes hasta aspirantes a baristas, pueden obtener fácilmente un espresso perfecto. ¡Compra la tuya acá!' ,
caracteristicas: 'Molino con 30 Configuraciones de molienda;Temperatura Inteligente de Colado;Bomba Italiana con 15 Bares de presión;Poderoso tubo de vapor que provee una microespuma para crear lattes y cappuccinos;Panel de control fácil de utilizar e intuitivo',
precio: '$ 2.199.900' },

{ id: 3 , 
nombre_producto: 'Ventilador' , 
nombre_completo : 'Ventilador de Piso SAMURAI Tropical Plus Negro' ,
marca : 'SAMURAI' ,
urlImage: './imagenes/3.jpg', 
description: 'Este ventilador de 18 pulgadas cuenta con 3 velocidades que permiten elegir el flujo de aire deseado. Teniendo en cuenta que sus niveles de ruido son bajos. Tiene un potente flujo de aire, ya que su motor es de 70W. Sus Mallas son muy seguras ya que no entran en contacto con sus helices. Además, sus mallas frontales son removibles, facilitanto la limpieza de los mismos. Cuentan con una oscilación vertical para una mayor y mejor distibución del aire. cuentan con un fácil y seguro sistema que permite ajustar la inclinación vertical.' ,
caracteristicas: 'Sus piezas son plásticas;Su base garantiza gran estabilidad.;Cuenta con 3 aspas;Producto fabricado con manufactura Colombiana',
precio: '$ 199.900' },

{ id: 4 ,
nombre_producto: 'Lavadora' , 
nombre_completo : 'Lavadora SAMSUNG Carga Superior 19KG WA19T6260BY Gris' ,
marca : 'SAMSUNG' ,
urlImage: './imagenes/4.jpg', 
description: 'La lavadora carga superior de 19Kg Samsung te brinda una amplia capacidad de lavado que te permite reducir la frecuencia de uso, incluso puedes incluir artículos realmente grandes. Maneja un motor Digital Inverter con 20 años de garantía que te permite tener un desempeño más potente y consume menos energía. Además, puedes personalizar tu ciclo de lavado de acuerdo a tus necesidades. Así mismo, tiene un compartimiento que disuelve el detergente en polvo antes de echarlo a la lavadora.' ,
caracteristicas: '20 años de garantía en el motor Digital Inverter:El Magic Dispenser te permite lavar sin preocuparte por los residuos de jabón;La tecnología Digital Inverter brinda una mejor eficiencia energética, el ruido mínimo y un desempeño de larga duración;Revisa el envase del detergente para utilizar la cantidad justa del mismo',
precio: '$ 1.899.000' },

{ id: 5 , 
nombre_producto: 'Nevera' , 
nombre_completo : 'Nevera HACEB No Frost Congelador Superior 379 Litros Brutos Manija Externa N404SEME Gris Plomo' ,
marca : 'HACEB' ,
urlImage: './imagenes/5.jpg', 
description: 'La nevera HACEB No Frost de 379 Litros color Gris Plomo con su tecnología Vital Fresh que neutraliza la propagación de bacterias y cuida la salud de tu familia mientras mantiene tus alimentos frescos por más tiempo.* Además, cuenta con panel digital interno con control digital de temperatura y función de congelamiento rápido, sistema de bandejas independientes con control de humedad ¡Aprovecha esta oportunidad y renueva tu hogar con la mejor tecnología en conservación de alimentos! ¡Compra ya y disfruta la nevera HACEB!' ,
caracteristicas: 'Sistema de corrientes continuas de aire con frío uniforme;Luz LED que permite mayor visibilidad al interior;Control Digital Interactivo-Interno para ajustar temperatura;Tecnología Vital fresh: reduce la propagación de bacterias*;Bandejas independientes: separa mejor tus frutas y verduras',
precio: '$ 2.077.900' },

{ id: 6 , 
nombre_producto: 'Freidora' , 
nombre_completo : 'Freidora de Aire OSTER 4 Litros Digital Diamond Force Negro' ,
marca : 'OSTER' ,
urlImage: './imagenes/6.jpg', 
description: '¡Eleva la preparación de tus alimentos! La freidora de aire OSTER digital con capacidad de 4L incluye una bandeja de freír con aire extraíble con revestimiento antiadherente DiamondForce para más espacio y una fácil limpieza. Nuestro revestimiento de Oster DiamondForce está reforzado e infundido con partículas de diamante que forman una matriz estructural, creando un revestimiento 12 veces más duradero y resistente a rayaduras y hasta 15 veces más fácil de limpiar. Ven por la tuya!' ,
caracteristicas: 'DiamondForce un recubrimiento fuerte y superior al de cualquier otro.;El Diamondforce ayuda a que los alimentos tengan el sabor que te gusta.;Freír con aire usa hasta un 99,5% menos de aceite para comer saludable.;Bandeja de freír con aire extraíble para más espacio y fácil limpieza;7 funciones para las mejores preparaciones.',
precio: '$ 359.900' },

{ id: 7 , 
nombre_producto: 'Estufa' , 
nombre_completo : 'Estufa de Piso HACEB 4 Puestos Gas Natural Romero 50-Torre Negro' ,
marca : 'HACEB' ,
urlImage: './imagenes/7.jpg', 
description: 'La estufa Romero HACEB Torre negra gas natural, logra recetas más rápidas con su fogón 35% más potente y de manera segura con sus parrillas antideslizantes. Cocinar en el horno ahora será mejor gracias a su visor 65% más amplio y hazlo de forma segura evitando la fuga de gas. ¡Cómprala ahora! disfruta de las mejores recetas.' ,
caracteristicas: 'Ahorra tiempo cocinando. Fogón 35% más potente;Parrilla antideslizante, mayor estabilidad en recipientes.;Visor del horno 65% más amplio para seguir tus recetas;Encendido eléctrico de las fuentes de calor;Evita fugas de gas gracias al sistema de termoseguridad',
precio: '$ 620.900' },

{ id: 8 , 
nombre_producto: 'Aspiradora' , 
nombre_completo : 'Aspiradora ELECTROLUX STK14 Barredora Power Speed Plus Gris' ,
marca : 'ELECTROLUX' ,
urlImage: './imagenes/8.jpg', 
description: 'La Aspiradora Vertical con cable STK14 Electrolux Power Speed su hogar de manera simple y eficiente. Con 2 posibilidades de uso, como aspiradora vertical y manual, tiene 2 veces más poder de limpieza, y brinda un mayor cuidado a para su familia, ya que está equipado con Filtro HEPA Allergy Protect, que retiene alérgenos, ácaros y hongos, devolviendo más aire puro y seguro para su medio ambiente.' ,
caracteristicas: 'Boquilla para rincones y hendiduras depósito de 1,6 L ;aspiradora 2 en 1 llegando a lugares de dificil acceso ;Cable electrico de 5 metros ;El sistema de filtración HEPA devuelve un aire más limpio ;Alto poder de succión limpieza eficiente y completa.',
precio: '$ 169.900' },
    
]
